# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

#### 3. Create a null vector of size 10

In [3]:
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array

In [6]:
print("%d bytes" %(x.size*x.itemsize))

80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [9]:
np.info

In [ ]:
np?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [17]:
b=np.zeros(10)
b[4]=1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49

In [19]:
b=np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [22]:
b[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [26]:
print(np.flipud(b))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [29]:
c=np.arange(9)
c1=c.reshape(3,3)
print(c1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [75]:
d=np.array([1,2,0,0,4,0])
cond=d>0
temp=np.where(d>0)
print(temp)

(array([0, 1, 4], dtype=int64),)


In [73]:
d1=np.nonzero([1,2,0,0,4,0])
print(d1)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [37]:
e=np.identity(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
e=np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [41]:
f=np.random.random((3,3,3))
print(f)

[[[0.53007367 0.42048663 0.74920652]
  [0.81810305 0.21670822 0.85842991]
  [0.70367207 0.46097222 0.87854533]]

 [[0.7278083  0.65515823 0.52691932]
  [0.77602079 0.33175124 0.03777838]
  [0.60556894 0.06762704 0.97200867]]

 [[0.92033983 0.76385195 0.81289803]
  [0.71113967 0.21070707 0.40386003]
  [0.5980023  0.55923158 0.24674214]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [42]:
g=np.random.random((10,10))
print(g.min(),g.max())

0.0005554213497784843 0.9971785604320652


#### 14. Create a random vector of size 30 and find the mean value

In [44]:
h=np.random.random(30)
print(h.mean())

0.48942646819930136


#### 15. Create a 2d array with 1 on the border and 0 inside

In [67]:
i=np.ones((5,5))
i[1:-1,1:-1]=0
print(i)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [61]:
arr=np.ones((5,5))
arr=np.pad(arr,pad_width=1, mode='constant',constant_values=0)
print(arr)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [47]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [52]:
j=np.diag(1+np.arange(4),k=-1)
print(j)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [53]:
k=np.zeros((8,8), dtype=int)
k[1::2,::2]=1
k[::2,1::2]=1
print(k)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [56]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)
