In [4]:
import numpy as np

In [5]:
arr=np.array([[1,2,3],
              [4,2,5]])

In [6]:
type(arr)

numpy.ndarray

In [7]:
print(arr.ndim) #print no.of dimensions

2


In [8]:
print("shape of array:",arr.shape)

shape of array: (2, 3)


In [9]:
print("size of the arr:",arr.size) #print total no.of elements im array

size of the arr: 6


In [10]:
print("array stores elements of type:",arr.dtype)

array stores elements of type: int32


In [11]:
a=np.array([[1,2,3],
            [4,5,6]])

In [12]:
print(a)

[[1 2 3]
 [4 5 6]]


In [13]:
b=np.array((1,2,3))

In [14]:
print(b)

[1 2 3]


In [16]:
c=np.zeros((3,4))

In [17]:
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
d=np.full((2,3),5, dtype="complex")

In [21]:
print(d)

[[5. 5. 5.]
 [5. 5. 5.]]


In [24]:
e=np.ones((2,3), dtype="int")

In [26]:
print(*e)

[1 1 1] [1 1 1]


In [30]:
f=np.random.random((2,2))

In [28]:
print(f)

[[0.58466555 0.8273516 ]
 [0.81833883 0.94567573]]


In [31]:
g= np.arange(0, 30, 5) #create a sequence of integers from 0 to 30 with steps of 5

In [32]:
print(g)

[ 0  5 10 15 20 25]


In [33]:
g = np.linspace(0, 5, 10)
print("\nA sequential array with 10 values between 0 and 5:\n", g)



A sequential array with 10 values between 0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [52]:
arr1= np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])

In [64]:
newarr=arr1.reshape((3,2,2))

In [65]:
print(arr1)
print(newarr)

[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
[[[1 2]
  [3 4]]

 [[5 2]
  [4 2]]

 [[1 2]
  [0 1]]]


In [66]:
# flatten array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flarr = arr.flatten()
print("\nOriginal array:\n", arr)
print("Fattened array:\n", flarr)


Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


In [67]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

In [68]:
temp=arr[:2, ::2 ]#slicing the Array with first 2 rows and alternate columns(0 and 2)
print(temp)

[[-1.  0.]
 [ 4.  6.]]


In [69]:
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print("\nElements at indices (0, 3), (1, 2), (2, 1), (3, 0):\n", temp)



Elements at indices (0, 3), (1, 2), (2, 1), (3, 0):
 [4. 6. 0. 3.]


In [70]:
temp1=arr>2
temp=arr[temp1]
print(temp)

[4.  4.  6.  2.6 7.  8.  3.  4. ]


In [71]:
a=np.array([10,9,8,9], dtype='int')

In [72]:
print("adding 1 to each element in array:",a+1)

adding 1 to each element in array: [11 10  9 10]


In [73]:
print("subtract 2 from each element:",a-2)

subtract 2 from each element: [8 7 6 7]


In [74]:
print("mutltiply each element with 3:",a*3)

mutltiply each element with 3: [30 27 24 27]


In [75]:
print("division with 2",a/2)

division with 2 [5.  4.5 4.  4.5]


In [76]:
a *= 2
print("Doubled each element of original array:", a)


Doubled each element of original array: [20 18 16 18]


In [80]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [82]:
print("original array:\n",arr)
print("tranpose of array:\n",arr.T)

original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
tranpose of array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [83]:
print("Largest element is:", arr.max())
print("Row-wise maximum elements:", arr.max(axis = 1))

Largest element is: 9
Row-wise maximum elements: [3 6 9]


In [84]:
print("Column-wise minimum elements:", arr.min(axis = 0))

Column-wise minimum elements: [1 2 3]


In [85]:
print(arr.max(axis=0))

[7 8 9]


In [86]:
print("sum of the array is:",arr.sum())

sum of the array is: 45


In [87]:
print("Cumulative sum along each row:\n", arr.cumsum(axis = 1))

Cumulative sum along each row:
 [[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


In [88]:
print("Cumulative sum along each column:\n", arr.cumsum(axis = 0))

Cumulative sum along each column:
 [[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


In [89]:
a = np.array([[1, 2], 
              [3, 4]])
b = np.array([[4, 3], 
              [2, 1]])

In [90]:
print("addition of two arrays is",a+b)

addition of two arrays is [[5 5]
 [5 5]]


In [91]:
print("multiplication of two arrays is",a*b)

multiplication of two arrays is [[4 6]
 [6 4]]


In [93]:
print("multiplication of two matrix is",a.dot(b))

multiplication of two matrix is [[ 8  5]
 [20 13]]


In [94]:
a = np.array([0, np.pi/2, np.pi])

In [95]:
print("Sine values of array elements:", np.sin(a))


Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [96]:
# exponential values
a = np.array([0, 1, 2, 3])
print("Exponent of array elements:", np.exp(a))


Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]


In [97]:
# square root of array values
print("Square root of array elements:", np.sqrt(a))

Square root of array elements: [0.         1.         1.41421356 1.73205081]


In [98]:
a = np.array([[1, 4, 2],
              [3, 4,6],
              [0, -1, 5]])


In [101]:
# sorted array
print("Array elements in sorted order:\n", np.sort(a,axis = None))

Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]


In [102]:
# sorted array
print("row wise sorted order:\n", np.sort(a, axis = 1))


row wise sorted order:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]


In [104]:
print("Column wise sort by applying quiksort:\n", np.sort(a, axis = 0, kind = 'quiksort'))


Column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


In [113]:
dtypes=[('name','S10'),('grd_year',int),('cgpa',float)]

In [114]:
values=[('siri',2022,8.5),('vamshi',2022,9.0),('ahan',250,9.7)]

In [117]:
arr=np.array(values,dtype=dtypes)
print("sort the arry based on name:",np.sort(arr,order='name'))

sort the arry based on name: [(b'ahan',  250, 9.7) (b'siri', 2022, 8.5) (b'vamshi', 2022, 9. )]


In [119]:
print("Array sorted by grauation year and then cgpa:\n", np.sort(arr, order = ['grd_year', 'cgpa']))

Array sorted by grauation year and then cgpa:
 [(b'ahan',  250, 9.7) (b'siri', 2022, 8.5) (b'vamshi', 2022, 9. )]


In [120]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])


In [121]:
# vertical stacking
print("Vertical stacking:\n", np.vstack((a, b)))

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [122]:
# horizontal stacking
print("horizonta stacking:\n", np.hstack((a, b)))

horizonta stacking:
 [[1 2 5 6]
 [3 4 7 8]]


In [123]:
c=[9,10]

In [124]:
# stacking columns
print("\nColumn stacking:\n", np.column_stack((a, c)))



Column stacking:
 [[ 1  2  9]
 [ 3  4 10]]


In [126]:
# concatenation method 
print("\nConcatenating to 2nd axis:\n", np.concatenate((a, b), 0))


Concatenating to 2nd axis:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [127]:
print("Splitting along horizontal axis into 2 parts:\n", np.hsplit(a, 2))


Splitting along horizontal axis into 2 parts:
 [array([[1],
       [3]]), array([[2],
       [4]])]


In [128]:
# vertical splitting
print("\nSplitting along vertical axis into 2 parts:\n", np.vsplit(a, 2))


Splitting along vertical axis into 2 parts:
 [array([[1, 2]]), array([[3, 4]])]


In [129]:
b = np.array([1,2,3,4,5])

In [130]:
print(np.mean(b))

3.0


In [131]:
print(np.median(b))

3.0


In [136]:
print(np.mean(a,axis=1))

[1.5 3.5]


In [137]:
w=np.array([1,1,1,1,1])

In [139]:
print(np.average(b,weights=w))

3.0


In [141]:
u=np.mean(b)
myStd = np.sqrt(np.mean(abs(b-u)**2))
print(myStd)


1.4142135623730951


In [142]:
dev=np.std(b)

In [143]:
print(dev)

1.4142135623730951


In [144]:
v=myStd**2
print(v)
print(np.var(b))



2.0000000000000004
2.0
